name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with recursive submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Restore snarkjs files
        id: cache-snarkjs
        uses: actions/cache@v2
        with:
          path: ~/out
          key: ${{ runner.os }}-snarkjs-${{ hashFiles('circuits/**/*') }}-${{ hashFiles('ptau/*.ptau') }}
          restore-keys: |
            ${{ runner.os }}-snarkjs-
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build --if-present
      - name: Generate required snarkJS filess
        if: steps.cache-snarkjs.outputs.cache-hit != 'true'
        run: npm run generate-snarkjs
      - name: Run unit tests
        run: npm test

  flow:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with recursive submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Restore npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-v1-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Restore snarkjs files
        id: cache-snarkjs
        uses: actions/cache@v2
        with:
          path: out/**/*
          key: ${{ runner.os }}-snarkjs-v1-${{ hashFiles('circuits/**/*') }}-${{ hashFiles('ptau/*.ptau') }}
          restore-keys: |
            ${{ runner.os }}-snarkjs-
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build --if-present
      - name: Generate required snarkJS filess
        if: steps.cache-snarkjs.outputs.cache-hit != 'true'
        run: npm run generate-snarkjs
      - name: Run default flow
        run: npm run flow