name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with recursive submodules)
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build --if-present
      - name: Generate required snarkJS files
        run: npm run generate-snarkjs
      - name: Run unit tests
        run: npm test
      - name: Run test flow
        run: npm run flow